-- MySQL Script generated by MySQL Workbench
-- Thu Feb  3 03:12:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supertest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supertest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supertest` DEFAULT CHARACTER SET utf8 ;
USE `supertest` ;

-- -----------------------------------------------------
-- Table `supertest`.`collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`collection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supertest`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supertest`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `hex` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supertest`.`weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`weapon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `style` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `imageurl` VARCHAR(45) NOT NULL,
  `collection_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_weapon_collection1_idx` (`collection_id` ASC) VISIBLE,
  INDEX `fk_weapon_type1_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_weapon_color1_idx` (`color_id` ASC) VISIBLE,
  CONSTRAINT `fk_weapon_collection1`
    FOREIGN KEY (`collection_id`)
    REFERENCES `supertest`.`collection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_weapon_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `supertest`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_weapon_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `supertest`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supertest`.`description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`description` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT(500) NOT NULL,
  `language` VARCHAR(5) NOT NULL,
  `weapon_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_description_weapon1_idx` (`weapon_id` ASC) VISIBLE,
  CONSTRAINT `fk_description_weapon1`
    FOREIGN KEY (`weapon_id`)
    REFERENCES `supertest`.`weapon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supertest`.`case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`case` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `img` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supertest`.`case_has_weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supertest`.`case_has_weapon` (
  `case_id` INT NOT NULL AUTO_INCREMENT,
  `weapon_id` INT NOT NULL,
  PRIMARY KEY (`case_id`, `weapon_id`),
  INDEX `fk_case_has_weapon_weapon1_idx` (`weapon_id` ASC) VISIBLE,
  INDEX `fk_case_has_weapon_case_idx` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_case_has_weapon_case`
    FOREIGN KEY (`case_id`)
    REFERENCES `supertest`.`case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_has_weapon_weapon1`
    FOREIGN KEY (`weapon_id`)
    REFERENCES `supertest`.`weapon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
